### ISSUE TITLE
Support for FW 18.0.0

### ISSUE THREAD

**Issue by impeeza** [StarDustCFW/Logo-para-switch.Palomitas#11]
Firmware 18.0.0 is out and changed the module, the new patch have the ID "9D8D6EFEE01E97E95E00D573530C09CB5AB5B8A0" and decimal offset: 2031872

**Comment by Kronos2308** [comment]
[18.0.0 - 2.9](https://github.com/StarDustCFW/Logo-para-switch.Palomitas/releases/tag/2.9)
