### ISSUE TITLE
Original Logo Use

### ISSUE THREAD

**Issue by impeeza** [StarDustCFW/Logo-para-switch.Palomitas#12]
Hello there, I noted the file "logo.png" is included on the package but the code do not use it, if you use the comparison of processing image and logo.png to generate only needed patches the new patch will be smaller.

**Comment by Kronos2308** [comment]
```
    if len(sys.argv) > 3:
        old_logo = Image.open(sys.argv[3])
    else:
        old_logo = Image.open("logo.png")

    old_logo = old_logo.convert("RGBA")
```


to replace the originall image the logo.png is needed
since you have to conver the data off 2  images to ARGB  and using the offset dec compare the two datas give you a ips

**Comment by Kronos2308** [comment]
you meean instead off use the png fill his size with 0 ?

**Comment by impeeza** [comment]
Yes the Python script have the code to use "Old_Logo" but the HTA app do not parse that argument, so the created IPS files are always the biggest ones possible.

If you parse the Old_Logo on the code the IPS files will contain only the differences between original boot logo and the new one, so the IPS files will be the smallest possible.

**Comment by Kronos2308** [comment]
Yes but the in the code you can see that if argument 3 is not passed the scrip will use logo.png
```py
    if len(sys.argv) > 3:
        old_logo = Image.open(sys.argv[3])
    else:
        old_logo = Image.open("logo.png")

    old_logo = old_logo.convert("RGBA")
```

**Comment by impeeza** [comment]
Cool I see, but by example using the Palomitas Logo, with Logo-para-switch.Palomitas-v2.9.exe  the IPS files are bigger all of them are 438013 bytes long.  Executing the process manually to compare the original logo to the new one, the patches are 221568 bytes long

Attaching the manual ones and the palomita patches.
[Manual.zip](https://github.com/StarDustCFW/Logo-para-switch.Palomitas/files/14817487/Manual.zip)
[Palomitas.zip](https://github.com/StarDustCFW/Logo-para-switch.Palomitas/files/14817488/Palomitas.zip)

some how the actual code is not taking in account the Old Logo.

**Comment by Kronos2308** [comment]
with comand you use

**Comment by Kronos2308** [comment]
![imagen](https://github.com/StarDustCFW/Logo-para-switch.Palomitas/assets/36446521/4d7a16fe-a4b8-425d-8c30-86672938781f)

because i see the diferences an the are bigger

**Comment by Kronos2308** [comment]
you are rigth there wash an error in the code

**Comment by Kronos2308** [comment]
[Update code](https://github.com/StarDustCFW/Logo-para-switch.Palomitas/releases/tag/3.0)

**Comment by impeeza** [comment]
Los parches manuales, se crearon tomando como  base el Logo original (Old_Logo) y creando archivos IPS que convierten esa imágen en la nueva imágen, así solo se parcha lo que cambia no toda la imagen de 431 200 bytes, entonces en vez de crear un IPS de 438 013 qué es lo que se necesita para parchear todos los 431 200 bytes, se crean IPS más pequeños.

en python uso estos comandos:



```
    import io
    import ips
    import argparse
    from pathlib import Path
    from PIL import Image


    parser = argparse.ArgumentParser()
    parser.add_argument("patches_dir", help="The directory where the generated patches will be dumped", type=Path)
    parser.add_argument("new_logo", help="The new logo image", type=Path)
    parser.add_argument("-o", "--old_logo", help="The original logo image", type=Path, default=None)



    old_logo = Image.open(args.old_logo).convert("RGBA")
    new_logo = Image.open(args.new_logo).convert("RGBA")
    base_patch = ips.Patch()
    base_patch = ips.Patch.create(old_logo.tobytes(), new_logo.tobytes())
    for build_id, offset in patch_info.items():
        tmp_p = ips.Patch()
        for r in base_patch.records:
            tmp_p.add_record(r.offset + offset, r.content, r.rle_size)
        with Path(args.patches_dir, f"{build_id}.ips").open("wb") as f:
            f.write(bytes(tmp_p))
```

en el código `offset` viene de una tabla donde están los nombres de los archivos IPS y el offset de cada uno, parecido a lo que tiene el archivo data

**Comment by Kronos2308** [comment]
Yes check pito.py (I change the code completely )I have something similar 
Just that in pito you can pass the id and offset concatenated to generate a single file 
Or pass the data.txt to generate all off them

**Comment by impeeza** [comment]
Excelente, saludos desde Colombia.
