### ISSUE TITLE
some issues and idea

### ISSUE THREAD

**Issue by chronoss09** [StarDustCFW/Logo-para-switch.Palomitas#2]
Here is my idea : 
- Drag'n'drop image file on the program
- Create ips for 10.x directly, no one is on old version and i think, ips work on all fw
- Create a ips folder at the same folder where is your image

I have a script error at the end of the convertor and it give me an empty ips folder : 
![Capture](https://user-images.githubusercontent.com/17669980/91671300-cd5d9100-eb25-11ea-8f3a-7ffc25d17744.PNG)

**Comment by Kronos2308** [comment]
You can't drag and drop there is nothing listening for that use the browse button

**Comment by Kronos2308** [comment]
the 1.2 you can select the firm
