### ISSUE TITLE
Error si la ruta de la imagen tiene espacios

### ISSUE THREAD

**Issue by impeeza** [StarDustCFW/Logo-para-switch.Palomitas#4]
Hola gracias, por este gran trabajo.

Al usar el proceso, si se selecciona una imagen que tenga un espacio en la ruta completa de su nombre, el proceso falla con el error:
![image](https://user-images.githubusercontent.com/41979604/115942809-97cd3580-a471-11eb-8a50-f6010a11489e.png)

si se usa una ruta igual de larga pero sin espacios funciona sin problema:
![image](https://user-images.githubusercontent.com/41979604/115942852-d19e3c00-a471-11eb-92c6-092b85b33c91.png)

supongo que tiene que ver con los comandos que se ejecutan, lo ideal sería colocar la ruta completa del archivo orígen entre comillas dobles para que los comandos no le separe como dos parámetros diferentes.

**Comment by impeeza** [comment]
Intenté crear un pull request pero no tengo permiso, el hta modificado es:

[Crear_logo_Rutas.zip](https://github.com/StarDustCFW/Logo-para-switch.Palomitas/files/6368808/Crear_logo_Rutas.zip)

Los únicos cambios son:

![image](https://user-images.githubusercontent.com/41979604/115943450-a74e7d80-a475-11eb-96e2-4971ad1867a9.png)

**Comment by Kronos2308** [comment]
ok arreglado grasias

**Comment by Kronos2308** [comment]
https://github.com/StarDustCFW/Logo-para-switch.Palomitas/releases/tag/1.8
