### ISSUE TITLE
Firmware 14.0.0 Support

### ISSUE THREAD

**Issue by impeeza** [StarDustCFW/Logo-para-switch.Palomitas#9]
Hi I did update to firmware 14.0.0 but no generated files works on it.  Thanks.

**Comment by Kronos2308** [comment]
Yes because the files for 14 are not generatted yet,
I will update the app and add support for 14

**Comment by Kronos2308** [comment]
https://github.com/StarDustCFW/Logo-para-switch.Palomitas/releases/tag/2.2
